Remove oneliners

diff --git a/gitops/deploy/push_image.yaml b/gitops/deploy/push_image.yaml
--- a/gitops/deploy/push_image.yaml
+++ b/gitops/deploy/push_image.yaml
@@ -50,7 +50,10 @@ jobs:
             set -e
             set -x
             ARTIFACT_PATH="$(Pipeline.Workspace)/${{ parameters.serviceName }}/${{ parameters.serviceName }}_$(shortCommitHash).tar.gz"
-            [[ ! -f "${ARTIFACT_PATH}" ]] && echo "Missing artifact file ($ARTIFACT_PATH) from CI pipeline, did you trigger this pipeline manually?" && exit 1
+            if [ ! -f "${ARTIFACT_PATH}" ]; then
+                echo "Missing artifact file ($ARTIFACT_PATH) from CI pipeline, did you trigger this pipeline manually?"
+                exit 1
+            fi
             IMAGE_ID="${{ parameters.serviceName }}:$(shortCommitHash)"
             IMAGE_ID_FULL="${{ parameters.acrName }}.azure.io/${{ parameters.imagePathPrefix }}/${IMAGE_ID}"
             az acr login -n "${{ parameters.acrName }}"
