Store all config in one file
* The changes are backwards compatible, we are setting a few default values
but won't change anything

diff --git a/gitops-v2/new/push.yaml b/gitops-v2/new/push.yaml
--- a/gitops-v2/new/push.yaml
+++ b/gitops-v2/new/push.yaml
@@ -9,8 +9,16 @@ parameters:
     type: string
   - name: azureSubscription
     type: string
+    default: ""
   - name: acrName
     type: string
+    default: ""
+  - name: awsServiceConnection
+    type: string
+    default: ""
+  - name: awsRegion
+    type: string
+    default: ""
   - name: imagePathPrefix
     type: string
     default: ""
@@ -34,9 +42,11 @@ jobs:
           # https://developercommunity.visualstudio.com/t/cannot-directly-access-release-pipeline-variables/433796
           SOURCE_VERSION_KEY="RESOURCES_PIPELINE_${SERVICE_NAME^^}_SOURCECOMMIT"
           SOURCE_VERSION=$(env | grep -e "^${SOURCE_VERSION_KEY}" | cut -d= -f2)
+          SHA_SHORT=${SOURCE_VERSION:0:7}
           IMAGE_ID=${SERVICE_NAME}:${SOURCE_VERSION:0:7}
           ARTIFACT_FILE_NAME=${IMAGE_ID/:/_}.tar.gz
           echo "##vso[task.setvariable variable=imageId]$IMAGE_ID"
+          echo "##vso[task.setvariable variable=shaShort]$SHA_SHORT"
           echo "##vso[task.setvariable variable=artifactFileName]$ARTIFACT_FILE_NAME"
 
           PROJECT_ID_KEY="RESOURCES_PIPELINE_${SERVICE_NAME^^}_PROJECTID"
@@ -51,6 +61,7 @@ jobs:
 
           echo "Debug:"
           echo "imageId (IMAGE_ID): $IMAGE_ID"
+          echo "shaShort (SHA_SHORT): $SHA_SHORT"
           echo "artifactFileName (ARTIFACT_FILE_NAME): $ARTIFACT_FILE_NAME"
           echo "projectId (PROJECT_ID): $PROJECT_ID"
           echo "pipelineId (PIPELINE_ID): $PIPELINE_ID"
@@ -71,7 +82,7 @@ jobs:
           targetPath: "$(Pipeline.Workspace)"
 
       - task: AzureCLI@2
-        displayName: "Push image to ACR"
+        displayName: "Get ACR login info"
         inputs:
           azureSubscription: ${{ parameters.azureSubscription }}
           addSpnToEnvironment: true
@@ -79,30 +90,86 @@ jobs:
           scriptLocation: inlineScript
           scriptType: bash
           inlineScript: |
-            set -ex
+            set -e
 
-            WORKSPACE=$(Pipeline.Workspace)
             SERVICE_NAME=$(resources.triggeringAlias)
             IMAGE_ID=$(imageId)
             IMAGE_PATH_PREFIX=${{ parameters.imagePathPrefix }}
             ACR_NAME=${{ parameters.acrName }}
-            EXTRA_TAG=${{ parameters.extraTag }}
 
-            ARTIFACT_PATH="${WORKSPACE}/${SERVICE_NAME}/${ARTIFACT_FILE_NAME}"
-            if [[ ! -f "${ARTIFACT_PATH}" ]]
-            then
-                echo "Missing artifact file ($ARTIFACT_PATH) from CI pipeline, did you trigger this pipeline manually?"
-                exit 1
-            fi
             IMAGE_ID_FULL="${ACR_NAME}.azurecr.io/${IMAGE_PATH_PREFIX}/${IMAGE_ID}"
-            az acr login -n "${ACR_NAME}"
-            docker load < $ARTIFACT_PATH
+            # Get token and store it in variables
+            az acr login -n "${ACR_NAME}" -t > tmp.json
+            TOKEN=$(cat tmp.json |jq -r .accessToken)
+            SERVER=$(cat tmp.json |jq -r .loginServer)
+
+            echo "##vso[task.setvariable variable=token]$TOKEN"
+            echo "##vso[task.setvariable variable=server]$SERVER"
+        condition: ne('${{ parameters.azureSubscription }}', '')
+
+      - task: AmazonWebServices.aws-vsts-tools.AWSShellScript.AWSShellScript@1
+        displayName: "Get ECR login info"
+        inputs:
+          workingDirectory: "."
+          awsCredentials: ${{ parameters.awsServiceConnection }}
+          regionName: ${{ parameters.awsRegion }}
+          scriptType: inline
+          inlineScript: |
+            set -e
+
+            aws ecr describe-repositories --repository-names ${SERVICE_NAME} || aws ecr create-repository --repository-name ${SERVICE_NAME} --image-scanning-configuration scanOnPush=true
+            SERVER=$(aws ecr describe-repositories --repository-names ${SERVICE_NAME} | jq -r '.repositories[0].repositoryUri')
+            TOKEN=$(aws ecr get-login-password --region ${AWS_REGION})
+
+            echo "##vso[task.setvariable variable=token]$TOKEN"
+            echo "##vso[task.setvariable variable=server]$SERVER"
+        env:
+          SERVICE_NAME: $(resources.triggeringAlias)
+        condition: ne('${{ parameters.awsRegion }}', '')
+
+      - bash: |
+          set -e
+          WORKSPACE=$(Pipeline.Workspace)
+          EXTRA_TAG=${{ parameters.extraTag }}
+          SHA_SHORT=$(shaShort)
+          TOKEN=$(token)
+          SERVER=$(server)
+          ACR_NAME=${{ parameters.acrName }}
+          IMAGE_PATH_PREFIX=${{ parameters.imagePathPrefix }}
+          IMAGE_ID_FULL="${ACR_NAME}.azurecr.io/${IMAGE_PATH_PREFIX}/${IMAGE_ID}"
+
+          ARTIFACT_PATH="${WORKSPACE}/${SERVICE_NAME}/${ARTIFACT_FILE_NAME}"
+          if [[ ! -f "${ARTIFACT_PATH}" ]]
+          then
+              echo "Missing artifact file ($ARTIFACT_PATH) from CI pipeline, did you trigger this pipeline manually?"
+              exit 1
+          fi
+
+          docker load < $ARTIFACT_PATH
+
+          # Run AWS
+          if [[ ${{ parameters.awsRegion }} != "" ]]
+          then
+            docker login -u AWS -p $TOKEN $SERVER
+            docker tag $(imageId) ${SERVER}:${SHA_SHORT}
+            docker push ${SERVER}:${SHA_SHORT}
+          fi
+
+          # Run Azure
+          if [[ $IMAGE_PATH_PREFIX != "" ]]
+          then
+            docker login -u 00000000-0000-0000-0000-000000000000 -p $TOKEN $SERVER
             docker tag $(imageId) "${IMAGE_ID_FULL}"
             docker push "${IMAGE_ID_FULL}"
-            if [[ "${EXTRA_TAG}" != "" ]]
-            then
-              docker tag ${SERVICE_NAME}:${EXTRA_TAG}
-              docker push ${SERVICE_NAME}:${EXTRA_TAG}
-            fi
+          fi
+
+          if [[ "${EXTRA_TAG}" != "" ]]
+          then
+            docker tag ${SERVICE_NAME}:${EXTRA_TAG}
+            docker push ${SERVICE_NAME}:${EXTRA_TAG}
+          fi
+
+        displayName: "Push image to container registry in ${{ parameters.environment }}"
         env:
+          SERVICE_NAME: $(resources.triggeringAlias)
           ARTIFACT_FILE_NAME: $(artifactFileName)
